DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT",
    "content": {
        "name": "Nanatole",
        "number": "0444 44 47 19"
    }
}